version: "3.8"

services:
  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=http://elasticsearch:9200
    ports:
      - "9411:9411"
    networks:
      - otel-network

  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - otel-network
    command: ["--js"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - otel-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    volumes:
      - ./docker/otlp/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    command: --config=/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
    networks:
      - otel-network

  svc-nats:
    build:
      dockerfile: ../docker/svc/Dockerfile
      context: ./svc-nats
    container_name: svc-nats
    volumes:
      - ./svc-nats:/app
      - /app/node_modules
    environment:
      - NATS_ENDPOINT=nats://nats:4222
      - OTLP_COLLECTOR_ENDPOINT=http://otel-collector:4318/v1/traces
      - SERVICE_NAME=svc-nats
    depends_on:
      - nats
      - otel-collector
    networks:
      - otel-network
    ports:
      - 9221:9229

  svc-http:
    build:
      dockerfile: ../docker/svc/Dockerfile
      context: ./svc-http
    container_name: svc-http
    volumes:
      - ./svc-http:/app
      - /app/node_modules
    environment:
      - NATS_ENDPOINT=nats://nats:4222
      - OTLP_COLLECTOR_ENDPOINT=http://otel-collector:4318/v1/traces
      - SERVICE_NAME=svc-http
    depends_on:
      - nats
      - otel-collector
    networks:
      - otel-network
    ports:
      - 3000:3000
      - 9220:9229

networks:
  otel-network:
    driver: bridge
