receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: "0.0.0.0:4318"
exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin, debug]
